version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8.11-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
